<?php
/**
 *  Namespace Autoload
 *  Copyright (C) 2011  Korstiaan de Ridder <korstiaan [at] korstiaan.com>
 *
 *	This file is part of Namespace Autoload.
 *
 *  Namespace Autoload is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Namespace Autoload is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Namespace Autoload.  If not, see <http://www.gnu.org/licenses/>.
 */

/** 
 * Implementation of hook_boot()
 */
function nsautoload_boot()
{
	spl_autoload_register(function($class){
		$expl 		= explode('\\',$class);
		
		if (count($expl) !== 2) return;
		
		$module 	= array_shift($expl);			
		$className 	= array_pop($expl);
		
		module_load_include('inc', $module,'class'.DIRECTORY_SEPARATOR."{$className}.class");			
	});
}
