<?php
/**
 *  Namespace Autoload
 *  Copyright (C) 2011-2012  Korstiaan de Ridder <korstiaan [at] korstiaan.com>
 *
 *	This file is part of Namespace Autoload.
 *
 *  Namespace Autoload is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Namespace Autoload is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Namespace Autoload.  If not, see <http://www.gnu.org/licenses/>.
 */

/** 
 * Implementation of hook_boot()
 */
function nsautoload_boot()
{
	_nsautoload_autoload();	
}

/** 
 * Implementation of hook_enable()
 */
function nsautoload_enable()
{
	_nsautoload_autoload();
}


function _nsautoload_autoload()
{
	static $done = null; if (true === $done) return; $done = true;

	spl_autoload_register(function($class){
		$expl = explode('\\',$class);
			
		if (2 === count($expl)) {
			// Locate Foo\Bar in foo/class/bar.class.inc  
			$module 	= strtolower(reset($expl));			
			$className 	= strtolower(end($expl));
			$file		= DRUPAL_ROOT.DIRECTORY_SEPARATOR.drupal_get_path('module', $module).DIRECTORY_SEPARATOR.'class'.DIRECTORY_SEPARATOR."{$className}.class.inc";
			if (file_exists($file)) {
				require $file;
			}
		}	
		if (1 !== count($expl)) {
			// Locate FooBar\Crux\Class in foo_bar/FooBar/Crux/Class.php
			$module 	= strtolower(preg_replace('/(?<=\\w)(?=[A-Z])/','_$1', $expl[0]));
			$classPath	= str_replace('_', DIRECTORY_SEPARATOR, array_pop($expl));	
			$file		= 
				DRUPAL_ROOT.
				DIRECTORY_SEPARATOR.
				drupal_get_path('module', $module).
				DIRECTORY_SEPARATOR.
				implode(DIRECTORY_SEPARATOR, $expl).
				DIRECTORY_SEPARATOR.
				$classPath.
				'.php'
			;
			
			if (file_exists($file)) {
				require $file;
			}						
		}
	});	
}
