<?php
/**
 * This file is part of nsautoload
 *
 * (c) Korstiaan de Ridder <korstiaan@korstiaan.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

/** 
 * Implementation of hook_boot()
 */
use Nsautoload\Nsautoload;
function nsautoload_boot()
{
	_nsautoload_autoload();	
}

/** 
 * Implementation of hook_enable()
 */
function nsautoload_enable()
{
	_nsautoload_autoload();
}


function _nsautoload_autoload()
{
    static $done = null; if (true === $done) return; $done = true;

    if (!class_exists('\\Nsautoload\\Nsautoload')) {
        require __DIR__.DIRECTORY_SEPARATOR.'Nsautoload'.DIRECTORY_SEPARATOR.'Nsautoload.php';
    }
    $loader = new Nsautoload();
    $loader->register();
}
