<?php
/**
 * This file is part of nsautoload
 *
 * (c) Korstiaan de Ridder <korstiaan@korstiaan.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

use Nsautoload\Nsautoload;

/** 
 * Implementation of hook_boot()
 */
function nsautoload_boot()
{
    _nsautoload_register();    
}

/** 
 * Implementation of hook_enable()
 */
function nsautoload_enable()
{
    _nsautoload_register();
}

/**
 * Register the autoloader, but only once 
 */
function _nsautoload_register()
{
    static $done = null; if (true === $done) return; $done = true;

    if (!class_exists('\\Nsautoload\\Nsautoload')) {
        require __DIR__.DIRECTORY_SEPARATOR.'Nsautoload'.DIRECTORY_SEPARATOR.'Nsautoload.php';
    }
    
    $loader = new Nsautoload();
    $loader->register();
}
